### ISSUE TITLE
Provide version with ES modules

### ISSUE THREAD

**Issue by OliverJAsh** [devexperts/remote-data-ts#41]
fp-ts provides a version with ES modules (specified via `module` in `package.jon`), which means tree shaking can work.

What do you think about doing the same thing for this package?

For context: I have a PR to add this library to unsplash.com, but I noticed it's currently bundling all of `io-ts` (because IIUC, tree shaking can't work with CommonJS), even though we're not using any of the io-ts helpers.

**Comment by OliverJAsh** [comment]
My workaround for now is to import from the submodule:

```ts
import * as RemoteData from '@devexperts/remote-data-ts/dist/remote-data';
```

Of course this still means we might be importing more than we need, but at least it avoids the `io-ts` import.

**Comment by raveclassic** [comment]
Hi, @OliverJAsh 
> What do you think about doing the same thing for this package?

I'm definitely for it! 
But I'm not sure I have time for it at the moment, would you like to participate? :)

**Comment by OliverJAsh** [comment]
Absolutely! https://github.com/devexperts/remote-data-ts/pull/42
