### ISSUE TITLE
`TaskRemoteData`

### ISSUE THREAD

**Issue by Rawnly** [devexperts/remote-data-ts#73]
Hello I'm trying to migrate from `Either` to `RemoteData` but I find hard to replace `TaskEither`. I was wonder if is possible to add a `TaskRemoteData` type. I [tried myself](https://gist.github.com/Rawnly/a5a1bcf81208df42ba971c4a23f4b986) (fp newbie) and I have something working (for my specific usage) but it isn't very complete (it doesn't even fully satisfy `Monad` type).

As non-advanced user take my words with care, maybe I don't have the right "perspective".

**Comment by ZUGAZ** [comment]
`I was wonder if is possible to add a TaskRemoteData type. `
This repo is only about `RemoteData`. To implement `TaskRemoteData` here would be out-of-scope. Your code looks promising. I suggest to create a project for it :)
